-- Run in Snowsight worksheet

USE ROLE ACCOUNTADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS NOAA_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Database + schemas (medallion pattern)
CREATE DATABASE IF NOT EXISTS NOAA_DB;

CREATE SCHEMA IF NOT EXISTS NOAA_DB.RAW;
CREATE SCHEMA IF NOT EXISTS NOAA_DB.CLEAN;
CREATE SCHEMA IF NOT EXISTS NOAA_DB.SERVING;

-- Dedicated role + user (good portfolio practice)
CREATE ROLE IF NOT EXISTS NOAA_ENGINEER;
GRANT USAGE ON WAREHOUSE NOAA_WH TO ROLE NOAA_ENGINEER;
GRANT ALL ON DATABASE NOAA_DB TO ROLE NOAA_ENGINEER;
GRANT ALL ON ALL SCHEMAS IN DATABASE NOAA_DB TO ROLE NOAA_ENGINEER;

CREATE USER IF NOT EXISTS noaa_svc_user
  PASSWORD = 'StrongPass123!'
  DEFAULT_ROLE = NOAA_ENGINEER
  DEFAULT_WAREHOUSE = NOAA_WH;

GRANT ROLE NOAA_ENGINEER TO USER noaa_svc_user;